//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResearchForSqlServerWithEF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableB
    {
        public Nullable<bool> ColumnA { get; set; }
        public Nullable<bool> ColumnB { get; set; }
        public Nullable<bool> ColumnC { get; set; }
        public string LineName { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public long TableAId { get; set; }
        public int NumberOfProcess { get; set; }
        public Nullable<System.DateTime> DateTimeNullable { get; set; }
        public System.DateTime DateTime { get; set; }
    }
}
